// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eewtfbzquosjjnmvqeyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVld3RmYnpxdW9zampubXZxZXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODQyMzMsImV4cCI6MjA1ODU2MDIzM30.NmQ0zX1DrgiA8PolLi0JxVa8I04EmRVtp5b1X-gSm8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);